### PR TITLE
Bug Update on features and stability and performance

### LINKED ISSUE #56: Caught by controller[0]: TypeError: Cannot read property 'uptime' of undefined
Hi,
i`m using Proxmox 6.1 and the adapter seems to work no more for this verion (before used 5.4, Adapter worked).
I`m receiving following error messages:
`

host.ioBroker2 | 2020-03-31 08:30:37.081 | info | Restart adapter system.adapter.proxmox.0 because enabled
-- | -- | -- | --
host.ioBroker2 | 2020-03-31 08:30:37.081 | info | instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
host.ioBroker2 | 2020-03-31 08:30:37.081 | error | Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught  by controller[0]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
host.ioBroker2 | 2020-03-31 08:30:37.079 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:342:27
host.ioBroker2 | 2020-03-31 08:30:37.079 | error | Caught by controller[0]: TypeError: Cannot read property 'uptime' of undefined
proxmox.0 | 2020-03-31 08:30:36.551 | info | (18007) Terminated (NO_ERROR): Without reason

`
Please help :) Thanks MeisterTR

### LINKED ISSUE #61: Add ioDelay as attribute of host
Hi,
I would like to keep an eye on the iodelay of my proxmox host. Is it possible to add it to the values of the adapter?

Best
Martin

### LINKED ISSUE #63: remove widget and vis restart from io-package
remove the widget directory if you do not defined any real widget and remove the vis restart from the io-package

### LINKED ISSUE #66: Allow to enter a list of IPs für proxmox hosts and try then till someone works (also on reconnects)
With a cluster basically and host could go offline, so it is not good to only have one IP to enter in the config. It would be better to allow entering e.g. a comma separated IP list and then on connection simply try them until you find a working one. On disconnect simple do the same :-)

### LINKED ISSUE #67: Shared storages are requested per node faster then query inerval
I have some storages which are shared and also tried the new Prxmox BackupServer. Here I noticed that the adapter "checks" the storage per node partly once per second ...

pveproxy log:

```
192.168.178.97 - root@pam [31/07/2020:13:38:14 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 136
192.168.178.97 - root@pam [31/07/2020:13:38:21 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 136
192.168.178.97 - root@pam [31/07/2020:13:38:24 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 136
192.168.178.97 - root@pam [31/07/2020:13:38:27 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 136
192.168.178.97 - root@pam [31/07/2020:13:38:36 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 105
192.168.178.97 - root@pam [31/07/2020:13:38:37 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 105
192.168.178.97 - root@pam [31/07/2020:13:38:38 +0200] "GET /api2/json/nodes/pm1/storage/pbs/status HTTP/1.1" 200 105

```

### PR DESCRIPTION
**Pull request by Apollon77**
* fixes #56
* add iowait, fixes #61
* fixes #63
* add request cache fixes #67
* change from interval to timeouts, but still it is broken in itself; needs complete rewrite to promises or clean callbacks and error handling
* allow to enter list of ips/hostnames, fixes #66
* improve error handling
* update deps
* update tests
* hack in concurrency management for the cache in the pseudo Prmoise style which is used here
* optimize requesting shared ressource data 
* optimize and limit number of API calls - prevent duplicate calls and parsing

In fact this PR mostly brings the adapte rup to speed and prevents "Hammering" on the proxmox API. With my 7 Nuc cluaster queriing everything needed roughly 15-20s and used 28% CPU on the PVE host just for these requests and was also hammering on PBS which opened a big performance problem. New version is getting the same data, needs roughly 3s and only adds 4% CPU usage.

Still the code is (sorry to say it) very much strange and a complete refactoring would be the idea. Best is a rewrite to real promises, also for all the state and object creations and updates. it do not need to be async/await because that would most likely need too long with all these data. Also an Error in API request will simply make the current run "stop"because errors are not reacted on in most places.
... but the PR is for now better then nothing :)
Please check and test it together with me

### CODE REVIEW

**Comment by MeisterTR** [comment]
I am pretty happy happy for this pull. Because my installation is verry small (just 5 vms and one node) with this few vms you don't see the performance problems. A  complete refactoring would be cool but you now.... 

is this supporting more than one proxmox host?

is it possibple to fix this?
[https://travis-ci.org/github/iobroker-community-adapters/ioBroker.proxmox/jobs/715629274#L407](https://travis-ci.org/github/iobroker-community-adapters/ioBroker.proxmox/jobs/715629274#L407
)

looks pretty good

**Comment by Apollon77** [comment]
The testing shown work but is red on macOS and I do not understand why :-( but it is working.  For why testing fails I asked AlCalzone but he is on vacation

**Comment by Apollon77** [comment]
> is it possibple to fix this?
https://travis-ci.org/github/iobroker-community-adapters/ioBroker.proxmox/jobs/715629274#L407

This is just testing because the config is empty, but even if there would be an IP it would get an error... I would leave it. The other ide is a full testing with a simulated web browser ... but thats more effort :-)

As said testing on macOS sometimes breaks whyever -... but it works

**Comment by MeisterTR** [comment]
Ok

**Pull request merged**
